
name: 'Prisma Cloud Image Scan'
description: 'Run Prisma Cloud Twistcli'
inputs:
  registry:
    description: 'Docker registry'
    required: true
  repository:
    description: 'Docker repository'
    required: true
  tag:
    description: 'Docker repository tag'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'